/* Inventario real del Salón de Spinning (levantamiento del 7-oct-2026, Inventario_Spinning_Salon_1.xlsx).
   Se carga una sola vez desde Equipos -> "Cargar inventario de Spinning". Cada id es fijo (spin-XX): volver a cargarlo no duplica. */
var INVENTARIO_SPINNING = [
 {
  "id": "spin-02",
  "nombre": "Bicicleta 2",
  "foto": "spinning-02.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve base frontal",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Limpieza + sellador",
  "material": "Anticorrosivo + lija"
 },
 {
  "id": "spin-03",
  "nombre": "Bicicleta 3",
  "foto": "spinning-03.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Revisar tensión pedal izquierdo",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Ajuste pedal",
  "material": "Grasa + llave pedal"
 },
 {
  "id": "spin-04",
  "nombre": "Bicicleta 4",
  "foto": "spinning-04.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido visible soporte frontal",
  "nivel": "Alta",
  "intervencion": "Correctivo",
  "correccion": "Lijado + pintura",
  "material": "Pintura industrial + convertidor óxido"
 },
 {
  "id": "spin-05",
  "nombre": "Bicicleta 5",
  "foto": "spinning-05.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Desgaste perilla ajuste",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Revisión y ajuste",
  "material": "Repuesto perilla"
 },
 {
  "id": "spin-07",
  "nombre": "Bicicleta 7",
  "foto": "spinning-07.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve base frontal",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Limpieza profunda",
  "material": "Anticorrosivo"
 },
 {
  "id": "spin-08",
  "nombre": "Bicicleta 8",
  "foto": "spinning-08.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve frontal",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Protección preventiva",
  "material": "Sellador"
 },
 {
  "id": "spin-09",
  "nombre": "Bicicleta 9",
  "foto": "spinning-09.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido + revisar pedal",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Ajuste + limpieza",
  "material": "Grasa + anticorrosivo"
 },
 {
  "id": "spin-10",
  "nombre": "Bicicleta 10",
  "foto": "spinning-10.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Corrosión visible + desgaste pedal",
  "nivel": "Media-Alta",
  "intervencion": "Correctivo",
  "correccion": "Mantenimiento estructural",
  "material": "Pintura + grasa + revisión pedal"
 },
 {
  "id": "spin-11",
  "nombre": "Bicicleta 11",
  "foto": "spinning-11.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructural visible",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Revisión general",
  "material": "Herramienta básica"
 },
 {
  "id": "spin-12",
  "nombre": "Bicicleta 12",
  "foto": "spinning-12.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Desgaste superficial poste asiento",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste y lubricación",
  "material": "Lubricante"
 },
 {
  "id": "spin-13",
  "nombre": "Bicicleta 13",
  "foto": "spinning-13.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Revisar pedal derecho",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Ajuste pedal",
  "material": "Grasa"
 },
 {
  "id": "spin-14",
  "nombre": "Bicicleta 14",
  "foto": "spinning-14.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Revisar alineación manubrio",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste alineación",
  "material": "Llaves Allen"
 },
 {
  "id": "spin-15",
  "nombre": "Bicicleta 15",
  "foto": "spinning-15.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Revisar alineación manubrio",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste alineación",
  "material": "Llaves Allen"
 },
 {
  "id": "spin-16",
  "nombre": "Bicicleta 16",
  "foto": "spinning-16.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve + revisar pedal",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Limpieza + ajuste",
  "material": "Anticorrosivo"
 },
 {
  "id": "spin-17",
  "nombre": "Bicicleta 17",
  "foto": "spinning-17.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Revisar alineación manubrio",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste alineación",
  "material": "Llaves Allen"
 },
 {
  "id": "spin-18",
  "nombre": "Bicicleta 18",
  "foto": "spinning-18.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve base frontal",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Protección estructural",
  "material": "Sellador"
 },
 {
  "id": "spin-19",
  "nombre": "Bicicleta 19",
  "foto": "spinning-19.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido más avanzado soporte frontal",
  "nivel": "Media-Alta",
  "intervencion": "Correctivo",
  "correccion": "Lijado + sellado",
  "material": "Convertidor óxido"
 },
 {
  "id": "spin-20",
  "nombre": "Bicicleta 20",
  "foto": "spinning-20.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve frontal",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Limpieza estructural",
  "material": "Anticorrosivo"
 },
 {
  "id": "spin-21",
  "nombre": "Bicicleta 21",
  "foto": "spinning-21.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Desgaste base frontal",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Protección preventiva",
  "material": "Sellador"
 },
 {
  "id": "spin-22",
  "nombre": "Bicicleta 22",
  "foto": "spinning-22.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido leve frontal",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Limpieza + protección",
  "material": "Anticorrosivo"
 },
 {
  "id": "spin-23",
  "nombre": "Bicicleta 23",
  "foto": "spinning-23.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructural visible",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Revisión general",
  "material": "Herramienta básica"
 },
 {
  "id": "spin-sn1",
  "nombre": "Bicicleta sin número 1",
  "foto": "spinning-sn1.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Óxido más avanzado soporte frontal",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste y lubricación",
  "material": "Lubricante"
 },
 {
  "id": "spin-sn2",
  "nombre": "Bicicleta sin número 2",
  "foto": "spinning-sn2.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructura visible",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Ajuste pedal",
  "material": "Grasa"
 },
 {
  "id": "spin-sn3",
  "nombre": "Bicicleta sin número 3",
  "foto": "spinning-sn3.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructura visible",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste alineación",
  "material": "Llaves Allen"
 },
 {
  "id": "spin-sn4",
  "nombre": "Bicicleta sin número 4",
  "foto": "spinning-sn4.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructura visible",
  "nivel": "Media",
  "intervencion": "Preventivo",
  "correccion": "Limpieza + ajuste",
  "material": "Anticorrosivo"
 },
 {
  "id": "spin-sn5",
  "nombre": "Bicicleta sin número 5",
  "foto": "spinning-sn5.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructura visible",
  "nivel": "Baja",
  "intervencion": "Preventivo",
  "correccion": "Ajuste alineación",
  "material": "Llaves Allen"
 },
 {
  "id": "spin-instructor",
  "nombre": "Bicicleta instructor",
  "foto": "spinning-instructor.jpg",
  "marca": "Spinner Ride",
  "tipo": "Bicicleta Indoor",
  "hallazgo": "Sin daño estructura visible",
  "nivel": "Alta",
  "intervencion": "Preventivo fijo",
  "correccion": "Servicio calendarizado trimestral",
  "material": "Kit mantenimiento completo"
 }
];
